# Site Settings
title: Cognitive Neuroscience of Human Verbal Communication
subtitle: Oganian Lab
email: oganianlab@posteo.de
description: >
  A guide to getting started with Jekyll.
baseurl: ''
url: 'http://localhost:4000'
twitter_username: yoganian
github_username:  HVCLab
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
