# config file changes only get applied after re-running jekyll
# Site Settings
title: Cognitive Neuroscience of Human Verbal Communication
subtitle: Oganian Lab
tabtitle: HVC Lab
email: oganianlab@posteo.de
description: 
baseurl: ''
url: 'http://HVCLab.github.io'
twitter_username: yoganian
github_username:  HVCLab
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
