# Site Settings
title: Start Jekyll
email: oganianlab@posteo.de
description: >
  A guide to getting started with Jekyll.
baseurl: '/HVCLab.github.io'
url: 'https://HVCLab.github.io'
twitter_username: yoganian
github_username:  HVCLab
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
